/**
 * PDF export utilities for goals
 */

import { jsPDF } from 'jspdf';
import { formatCurrency, type Goal, type Bucket } from '@/types';

// Bucket colors (RGB values)
const BUCKET_COLORS: Record<Bucket, { r: number; g: number; b: number }> = {
  safety: { r: 34, g: 197, b: 94 },   // Green
  growth: { r: 59, g: 130, b: 246 },  // Blue
  dream: { r: 168, g: 85, b: 247 },   // Purple
};

const BUCKET_LABELS: Record<string, Record<Bucket, string>> = {
  en: { safety: 'Safety', growth: 'Growth', dream: 'Dream' },
  es: { safety: 'Seguridad', growth: 'Crecimiento', dream: 'Sueño' },
};

interface PDFTranslations {
  title: string;
  generated: string;
  totalGoals: string;
  goal: string;
  goals: string;
  total: string;
  target: string;
  targetDate: string;
  whyItMatters: string;
  priority: string;
  noGoals: string;
  page: string;
  of: string;
  generatedBy: string;
}

const TRANSLATIONS: Record<string, PDFTranslations> = {
  en: {
    title: 'My Investment Goals',
    generated: 'Generated',
    totalGoals: 'Total Goals',
    goal: 'goal',
    goals: 'goals',
    total: 'Total',
    target: 'Target',
    targetDate: 'Target Date',
    whyItMatters: 'Why It Matters',
    priority: 'Priority',
    noGoals: 'No goals yet.',
    page: 'Page',
    of: 'of',
    generatedBy: 'Generated by Investment Goals App',
  },
  es: {
    title: 'Mis Metas de Inversión',
    generated: 'Generado',
    totalGoals: 'Total de Metas',
    goal: 'meta',
    goals: 'metas',
    total: 'Total',
    target: 'Objetivo',
    targetDate: 'Fecha Objetivo',
    whyItMatters: 'Por Qué Importa',
    priority: 'Prioridad',
    noGoals: 'Sin metas todavía.',
    page: 'Página',
    of: 'de',
    generatedBy: 'Generado por Investment Goals App',
  },
};

/**
 * Group goals by bucket
 */
function groupByBucket(goals: Goal[]): Record<Bucket, Goal[]> {
  return goals.reduce((acc, goal) => {
    acc[goal.bucket].push(goal);
    return acc;
  }, { safety: [], growth: [], dream: [] } as Record<Bucket, Goal[]>);
}

/**
 * Format date for PDF display
 */
function formatDate(date: Date | string, locale: string): string {
  return new Date(date).toLocaleDateString(locale === 'es' ? 'es-ES' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

/**
 * Generate PDF document from goals
 */
export function generateGoalsPDF(goals: Goal[], locale: string = 'en'): void {
  const t = TRANSLATIONS[locale] || TRANSLATIONS.en;
  const bucketLabels = BUCKET_LABELS[locale] || BUCKET_LABELS.en;

  // Create PDF document (A4 size)
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let y = margin;

  // Helper to check if we need a new page
  const checkNewPage = (neededSpace: number) => {
    if (y + neededSpace > pageHeight - 30) {
      doc.addPage();
      y = margin;
      return true;
    }
    return false;
  };

  // Helper to add page footer
  const addFooter = (pageNum: number, totalPages: number) => {
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `${t.page} ${pageNum} ${t.of} ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    doc.text(
      t.generatedBy,
      pageWidth / 2,
      pageHeight - 15,
      { align: 'center' }
    );
  };

  // ===== HEADER =====
  // Title
  doc.setFontSize(24);
  doc.setTextColor(23, 23, 23);
  doc.setFont('helvetica', 'bold');
  doc.text(t.title, margin, y);
  y += 10;

  // Generated date
  doc.setFontSize(10);
  doc.setTextColor(113, 113, 122);
  doc.setFont('helvetica', 'normal');
  const dateStr = formatDate(new Date(), locale);
  doc.text(`${t.generated}: ${dateStr}`, margin, y);
  y += 8;

  // Summary stats
  const totalAmount = goals.reduce((sum, g) => sum + g.amount, 0);
  const currency = goals[0]?.currency || 'USD';
  const goalsWord = goals.length === 1 ? t.goal : t.goals;

  doc.setFontSize(12);
  doc.setTextColor(23, 23, 23);
  doc.text(`${goals.length} ${goalsWord} · ${formatCurrency(totalAmount, currency)}`, margin, y);
  y += 12;

  // Divider line
  doc.setDrawColor(228, 228, 231);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // ===== GOALS BY BUCKET =====
  if (goals.length === 0) {
    doc.setFontSize(12);
    doc.setTextColor(113, 113, 122);
    doc.text(t.noGoals, margin, y);
  } else {
    const grouped = groupByBucket(goals);
    const bucketOrder: Bucket[] = ['safety', 'growth', 'dream'];

    for (const bucket of bucketOrder) {
      const bucketGoals = grouped[bucket];
      if (bucketGoals.length === 0) continue;

      checkNewPage(40);

      // Bucket header with colored bar
      const color = BUCKET_COLORS[bucket];
      doc.setFillColor(color.r, color.g, color.b);
      doc.rect(margin, y, 4, 8, 'F');

      doc.setFontSize(14);
      doc.setTextColor(23, 23, 23);
      doc.setFont('helvetica', 'bold');
      doc.text(bucketLabels[bucket], margin + 8, y + 6);
      y += 14;

      // Sort by priority
      const sorted = [...bucketGoals].sort((a, b) => a.priority - b.priority);

      for (const goal of sorted) {
        checkNewPage(50);

        // Goal card background
        doc.setFillColor(249, 250, 251);
        doc.setDrawColor(228, 228, 231);
        doc.roundedRect(margin, y, contentWidth, 40, 2, 2, 'FD');

        // Priority badge
        doc.setFillColor(color.r, color.g, color.b);
        doc.circle(margin + 8, y + 8, 4, 'F');
        doc.setFontSize(8);
        doc.setTextColor(255, 255, 255);
        doc.setFont('helvetica', 'bold');
        doc.text(`${goal.priority}`, margin + 8, y + 9.5, { align: 'center' });

        // Goal title
        doc.setFontSize(12);
        doc.setTextColor(23, 23, 23);
        doc.setFont('helvetica', 'bold');
        const titleMaxWidth = contentWidth - 80;
        const titleLines = doc.splitTextToSize(goal.title, titleMaxWidth);
        doc.text(titleLines[0], margin + 16, y + 9);

        // Amount (right side)
        doc.setFontSize(12);
        doc.setTextColor(color.r, color.g, color.b);
        doc.setFont('helvetica', 'bold');
        const amountText = formatCurrency(goal.amount, goal.currency);
        doc.text(amountText, pageWidth - margin - 4, y + 9, { align: 'right' });

        // Description (truncated)
        doc.setFontSize(9);
        doc.setTextColor(113, 113, 122);
        doc.setFont('helvetica', 'normal');
        const descMaxWidth = contentWidth - 16;
        const descLines = doc.splitTextToSize(goal.description, descMaxWidth);
        doc.text(descLines.slice(0, 2).join('\n'), margin + 8, y + 18);

        // Target date
        doc.setFontSize(9);
        doc.setTextColor(82, 82, 91);
        const targetDateText = `${t.targetDate}: ${formatDate(goal.targetDate, locale)}`;
        doc.text(targetDateText, margin + 8, y + 32);

        // Why it matters (if fits)
        if (goal.whyItMatters) {
          const whyMaxWidth = contentWidth - 100;
          const whyLines = doc.splitTextToSize(goal.whyItMatters, whyMaxWidth);
          doc.setFontSize(8);
          doc.setTextColor(113, 113, 122);
          doc.setFont('helvetica', 'italic');
          doc.text(whyLines[0], margin + 8, y + 38);
        }

        y += 46;
      }

      y += 6; // Space between buckets
    }
  }

  // Add footers to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(i, totalPages);
  }

  // Generate filename
  const timestamp = new Date().toISOString().split('T')[0];
  const filename = locale === 'es'
    ? `metas-inversion-${timestamp}.pdf`
    : `investment-goals-${timestamp}.pdf`;

  // Download the PDF
  doc.save(filename);
}
