import { GoalTemplate } from '@/types/goal';

export const GOAL_TEMPLATES: GoalTemplate[] = [
  // Safety Bucket Templates
  {
    id: 'emergency-fund',
    title: 'Emergency Fund',
    description: 'A financial safety net to cover unexpected expenses like medical bills or home repairs.',
    bucket: 'safety',
    suggestedAmountMin: 5000,
    suggestedAmountMax: 25000, // Roughly 3-6 months for many
    suggestedTimelineMonths: 6,
    sampleWhyItMatters: 'To provide peace of mind and prevent debt when life throws a curveball.',
    icon: 'shield-alert',
  },
  {
    id: 'health-insurance',
    title: 'Health Insurance Deductible',
    description: 'Savings set aside to cover your max out-of-pocket health costs.',
    bucket: 'safety',
    suggestedAmountMin: 1000,
    suggestedAmountMax: 5000,
    suggestedTimelineMonths: 3,
    sampleWhyItMatters: 'To ensure medical care is never delayed due to cost.',
    icon: 'heart-pulse',
  },
  {
    id: 'job-loss-buffer',
    title: 'Job Loss Buffer',
    description: 'Extended savings to cover living expenses during a career transition.',
    bucket: 'safety',
    suggestedAmountMin: 15000,
    suggestedAmountMax: 50000,
    suggestedTimelineMonths: 12,
    sampleWhyItMatters: 'To maintain my lifestyle and reduce stress while finding the right next career move.',
    icon: 'briefcase',
  },

  // Growth Bucket Templates
  {
    id: 'house-down-payment',
    title: 'House Down Payment',
    description: 'Savings for the initial payment on a new home.',
    bucket: 'growth',
    suggestedAmountMin: 20000,
    suggestedAmountMax: 100000,
    suggestedTimelineMonths: 48, // 4 years
    sampleWhyItMatters: 'To build equity and have a place to call my own.',
    icon: 'home',
  },
  {
    id: 'new-car',
    title: 'New Car',
    description: 'Funds to purchase a reliable vehicle.',
    bucket: 'growth',
    suggestedAmountMin: 15000,
    suggestedAmountMax: 40000,
    suggestedTimelineMonths: 36,
    sampleWhyItMatters: 'To have reliable transportation for work and family trips.',
    icon: 'car',
  },
  {
    id: 'wedding',
    title: 'Wedding',
    description: 'Budget for the ceremony, reception, and honeymoon.',
    bucket: 'growth',
    suggestedAmountMin: 10000,
    suggestedAmountMax: 50000,
    suggestedTimelineMonths: 18,
    sampleWhyItMatters: 'To celebrate our union with family and friends without starting marriage in debt.',
    icon: 'heart',
  },
  {
    id: 'education',
    title: 'Education / Certification',
    description: 'Investment in new skills, degree, or professional certification.',
    bucket: 'growth',
    suggestedAmountMin: 5000,
    suggestedAmountMax: 50000,
    suggestedTimelineMonths: 24,
    sampleWhyItMatters: 'To advance my career and increase my earning potential.',
    icon: 'graduation-cap',
  },
  {
    id: 'home-renovation',
    title: 'Home Renovation',
    description: 'Upgrades to improve comfort or value of your current home.',
    bucket: 'growth',
    suggestedAmountMin: 10000,
    suggestedAmountMax: 50000,
    suggestedTimelineMonths: 24,
    sampleWhyItMatters: 'To create a more functional and enjoyable living space.',
    icon: 'hammer',
  },

  // Dream Bucket Templates
  {
    id: 'luxury-vacation',
    title: 'Luxury Vacation',
    description: 'A once-in-a-lifetime trip or extended travel experience.',
    bucket: 'dream',
    suggestedAmountMin: 5000,
    suggestedAmountMax: 20000,
    suggestedTimelineMonths: 18,
    sampleWhyItMatters: 'To create lifelong memories and experience new cultures.',
    icon: 'plane',
  },
  {
    id: 'sabbatical',
    title: 'Sabbatical Year',
    description: 'Funding for a year off work to travel or pursue personal projects.',
    bucket: 'dream',
    suggestedAmountMin: 20000,
    suggestedAmountMax: 50000,
    suggestedTimelineMonths: 48,
    sampleWhyItMatters: 'To recharge and rediscover my passions outside of work.',
    icon: 'compass',
  },
  {
    id: 'start-business',
    title: 'Start a Business',
    description: 'Seed capital to launch a new venture.',
    bucket: 'dream',
    suggestedAmountMin: 10000,
    suggestedAmountMax: 100000,
    suggestedTimelineMonths: 36,
    sampleWhyItMatters: 'To build something of my own and achieve financial independence.',
    icon: 'rocket',
  },
  {
    id: 'early-retirement',
    title: 'Early Retirement Boost',
    description: 'Additional investment to accelerate retirement timeline.',
    bucket: 'dream',
    suggestedAmountMin: 50000,
    suggestedAmountMax: 500000,
    suggestedTimelineMonths: 120, // 10 years
    sampleWhyItMatters: 'To gain freedom of time sooner.',
    icon: 'sunset',
  },
];
